#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

string solve(int64_t N, vector<int64_t> &A, vector<int64_t> &B)
{
    double A_average = double(reduce(ALL(A))) / N,
           B_average = double(reduce(ALL(B))) / N;
    return A_average == B_average ? "same" : (A_average < B_average ? "B" : "A");
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    std::cin >> N;
    vector<int64_t> A(N), B(N);
    REP(i, N)
    {
        cin >> A[i];
    }
    REP(i, N)
    {
        cin >> B[i];
    }
    auto ans = solve(N, A, B);
    std::cout << ans << '\n';
    return 0;
}
