#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

vector<int64_t> solve(int Q, const std::vector<int64_t> &t, const std::vector<int64_t> &x)
{
    deque<int64_t> cards;
    vector<int64_t> ans;

    REP(i, Q)
    {
        switch (t[i])
        {
        case 1:
            cards.push_front(x[i]);
            break;
        case 2:
            cards.push_back(x[i]);
            break;
        case 3:
            ans.push_back(cards[x[i] - 1]);
            break;
        }
    }

    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int Q;
    std::cin >> Q;
    std::vector<int64_t> t(Q), x(Q);
    REP(i, Q)
    {
        std::cin >> t[i] >> x[i];
    }
    for (auto ans : solve(Q, t, x))
    {
        std::cout << ans << '\n';
    }
    return 0;
}
