#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


std::string solve(int64_t N, std::string S, int Q, const std::vector<int64_t> &t, const std::vector<int64_t> &x, const std::vector<char> &c) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    std::string S;
    int Q;
    std::cin >> N >> S >> Q;
    std::vector<int64_t> t(Q), x(Q);
    std::vector<char> c(Q);
    REP (i, Q) {
        std::cin >> t[i] >> x[i] >> c[i];
    }
    auto ans = solve(N, S, Q, t, x, c);
    std::cout << ans << '\n';
    return 0;
}
