#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int64_t N, int M, int64_t H, int64_t K, std::string S, const std::vector<int64_t> &x, const std::vector<int64_t> &y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    int M;
    int64_t H, K;
    std::string S;
    std::cin >> N >> M;
    std::vector<int64_t> x(M), y(M);
    std::cin >> H >> K >> S;
    REP (i, M) {
        std::cin >> x[i] >> y[i];
    }
    auto ans = solve(N, M, H, K, S, x, y);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
