#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    C = [None for _ in range(N)]
    M = random.randint(1, 1000)  # TODO: edit here
    D = [None for _ in range(M)]
    P = [None for _ in range(M + 1)]
    for i in range(N):
        C[i] = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    for i in range(M):
        D[i] = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    for i in range(M + 1):
        P[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, M)
    print(*[C[i] for i in range(N)])
    print(*[D[i] for i in range(M)])
    print(*[P[i] for i in range(M + 1)])


if __name__ == "__main__":
    main()
