#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, std::vector<int64_t> &A)
{
    int64_t ans = 0;
    auto ave = accumulate(ALL(A), 0LL) / N;
    sort(ALL(A));
    REP(i, N / 2)
    {
        auto n = min((ave - A[i]), (A[N - 1 - i] - ave));
        A[i] += n;
        A[N - 1 - i] -= n;
        ans += n;
    }
    int64_t n = 0;
    for (auto a : A)
    {
        n += abs(a - ave);
    }

    return ans + n / 2;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> A(N);
    REP(i, N)
    {
        std::cin >> A[i];
    }
    auto ans = solve(N, A);
    std::cout << ans << '\n';
    return 0;
}
