#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int N, const std::vector<std::string> &S)
{
    REP(i, N - 1)
    {
        REP3(j, i + 1, N)
        {
            auto s = S[i] + S[j], s_rev = s;
            ranges::reverse(s_rev);
            if (s == s_rev)
            {
                return true;
            }
            s = S[j] + S[i], s_rev = s;
            ranges::reverse(s_rev);
            if (s == s_rev)
            {
                return true;
            }
        }
    }
    return false;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<std::string> S(N);
    REP(i, N)
    {
        std::cin >> S[i];
    }
    auto ans = solve(N, S);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
