#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10**9)  # TODO: edit here
    M = random.randint(1, 1000)  # TODO: edit here
    l = [None for _ in range(M)]
    r = [None for _ in range(M)]
    a = [None for _ in range(M)]
    for i in range(M):
        l[i] = random.randint(1, 10**9)  # TODO: edit here
        r[i] = random.randint(1, 10**9)  # TODO: edit here
        a[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, M)
    for i in range(M):
        print(l[i], r[i], a[i])


if __name__ == "__main__":
    main()
