#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 998244353;
int64_t solve(int64_t N, int64_t M, int K, int L, const std::vector<int64_t> &A, const std::vector<int64_t> &B) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, M;
    int K, L;
    std::cin >> N >> M >> K;
    std::vector<int64_t> A(K);
    std::cin >> L;
    std::vector<int64_t> B(L);
    REP (i, K) {
        std::cin >> A[i];
    }
    REP (i, L) {
        std::cin >> B[i];
    }
    auto ans = solve(N, M, K, L, A, B);
    std::cout << ans << '\n';
    return 0;
}
