#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(auto H, auto W, auto K, const std::vector<std::vector<auto> > &s) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto H, W, K;
    std::cin >> H >> W;
    std::vector<std::vector<auto> > s(H + W + 4, std::vector<auto>((H + W + 4)));
    std::cin >> K;
    REP (j, H + 4) {
        REP (i, W) {
            std::cin >> s[i + j][i + j];
        }
    }
    auto ans = solve(H, W, K, s);
    REP (j, H + 4) {
        REP (i, W) {
            std::cout << a[i + j][i + j] << ' ';
        }
        std::cout << '\n';
    }
    return 0;
}
