#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

auto solve(int n, vector<pair<int64_t, int64_t>> ps)
{
    sort(ps.begin(), ps.end(), [](auto p1, auto p2)
         { return p1.second < p2.second; });
    return ps;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int n;
    std::cin >> n;
    vector<pair<int64_t, int64_t>> ps(n);
    for (auto &p : ps)
    {
        cin >> p.first >> p.second;
    }
    auto ans = solve(n, ps);
    for (auto a : ans)
    {
        std::cout << a.first << ' ' << a.second << '\n';
    }
    return 0;
}
