#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10**9)  # TODO: edit here
    M = random.randint(1, 1000)  # TODO: edit here
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i] = random.randint(1, 10**9)  # TODO: edit here
        v[i] = random.randint(1, 10**9)  # TODO: edit here
    K = random.randint(1, 1000)  # TODO: edit here
    x = [None for _ in range(K)]
    y = [None for _ in range(K)]
    for i in range(K):
        x[i] = random.randint(1, 10**9)  # TODO: edit here
        y[i] = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    p = [None for _ in range(Q)]
    q = [None for _ in range(Q)]
    for i in range(Q):
        p[i] = random.randint(1, 10**9)  # TODO: edit here
        q[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, M)
    for i in range(M):
        print(u[i], v[i])
    print(K)
    for i in range(K):
        print(x[i], y[i])
    print(Q)
    for i in range(Q):
        print(p[i], q[i])


if __name__ == "__main__":
    main()
