#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    x = [None for _ in range(Q)]
    y = [None for _ in range(Q)]
    z = [None for _ in range(Q)]
    w = [None for _ in range(Q)]
    for i in range(Q):
        x[i] = random.randint(1, 10**9)  # TODO: edit here
        y[i] = random.randint(1, 10**9)  # TODO: edit here
        z[i] = random.randint(1, 10**9)  # TODO: edit here
        w[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, Q)
    for i in range(Q):
        print(x[i], y[i], z[i], w[i])


if __name__ == "__main__":
    main()
