#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const int dist[] = {3, 1, 4, 1, 5, 9};
int64_t solve(char p, char q)
{
    auto [l, r] = minmax({dist + (p - 'A'), dist + (q - 'A')});
    return reduce(l, r);
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    char p, q;
    std::cin >> p >> q;
    auto ans = solve(p, q);
    std::cout << ans << '\n';
    return 0;
}
