#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W = random.randint(1, 10**9)  # TODO: edit here
    H = random.randint(1, 10**9)  # TODO: edit here
    N = random.randint(1, 1000)  # TODO: edit here
    p = [None for _ in range(N)]
    q = [None for _ in range(N)]
    for i in range(N):
        p[i] = random.randint(1, 10**9)  # TODO: edit here
        q[i] = random.randint(1, 10**9)  # TODO: edit here
    A = random.randint(1, 1000)  # TODO: edit here
    a = [None for _ in range(A)]
    for i in range(A):
        a[i] = random.randint(1, 10**9)  # TODO: edit here
    B = random.randint(1, 1000)  # TODO: edit here
    b = [None for _ in range(B)]
    for i in range(B):
        b[i] = random.randint(1, 10**9)  # TODO: edit here
    print(W, H)
    print(N)
    for i in range(N):
        print(p[i], q[i])
    print(A)
    print(*[a[i] for i in range(A)])
    print(B)
    print(*[b[i] for i in range(B)])


if __name__ == "__main__":
    main()
