#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int a, int64_t b, int c, const std::vector<std::string> &d, const std::vector<int64_t> &e, const std::vector<int64_t> &f, const std::vector<int64_t> &g, const std::vector<int64_t> &h) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int a;
    int64_t b;
    int c;
    std::cin >> a;
    std::vector<std::string> d(a);
    std::cin >> b >> c;
    std::vector<int64_t> e(c), f(c), g(c), h(c);
    REP (i, a) {
        std::cin >> d[i];
    }
    REP (i, c) {
        std::cin >> e[i] >> f[i] >> g[i] >> h[i];
    }
    auto ans = solve(a, b, c, d, e, f, g, h);
    REP (i, c) {
        std::cout << m[i] << '\n';
    }
    return 0;
}
