#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, int M, const std::vector<int64_t> &A, const std::vector<std::string> &S) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<std::string> S(N);
    std::cin >> M;
    std::vector<int64_t> A(M);
    REP (i, M) {
        std::cin >> A[i];
    }
    REP (i, N) {
        std::cin >> S[i];
    }
    auto ans = solve(N, M, A, S);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
