#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int64_t N, int M, int Q, const std::vector<int64_t> &L, const std::vector<int64_t> &R, const std::vector<int64_t> &p, const std::vector<int64_t> &q) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    int M, Q;
    std::cin >> N >> M;
    std::vector<int64_t> L(M), R(M);
    std::cin >> Q;
    std::vector<int64_t> p(Q), q(Q);
    REP (i, M) {
        std::cin >> L[i] >> R[i];
    }
    REP (i, Q) {
        std::cin >> p[i] >> q[i];
    }
    auto ans = solve(N, M, Q, L, R, p, q);
    REP (i, Q) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
