#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    AX = [None for _ in range(N)]
    AY = [None for _ in range(N)]
    BX = [None for _ in range(N)]
    BY = [None for _ in range(N)]
    T = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N):
        AX[i] = random.randint(1, 10**9)  # TODO: edit here
        AY[i] = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N):
        BX[i] = random.randint(1, 10**9)  # TODO: edit here
        BY[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, T)
    for i in range(N):
        print(AX[i], AY[i])
    for i in range(N):
        print(BX[i], BY[i])


if __name__ == "__main__":
    main()
