#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, const std::vector<int64_t> &x, int M, int64_t K, const std::vector<int64_t> &a) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    int64_t K;
    std::cin >> N;
    std::vector<int64_t> x(N);
    REP (i, N) {
        std::cin >> x[i];
    }
    std::cin >> M;
    std::vector<int64_t> a(M);
    std::cin >> K;
    REP (i, M) {
        std::cin >> a[i];
    }
    auto ans = solve(N, x, M, K, a);
    REP (i, N) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
