#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

std::pair<int64_t, int64_t> solve(int N, const std::vector<int64_t> &a)
{
    int N_COLOR = 8, COLOR_RANGE = 400;
    vector<int> colors(N_COLOR, 0);
    int all = 0;
    for (auto rating : a)
    {
        if (rating >= COLOR_RANGE * N_COLOR)
        {
            all++;
        }
        else
        {
            colors[rating / COLOR_RANGE] = 1;
        }
    }
    return {max(1, accumulate(ALL(colors), 0)), accumulate(ALL(colors), 0) + all};
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> a(N);
    REP(i, N)
    {
        std::cin >> a[i];
    }
    auto [d, e] = solve(N, a);
    std::cout << d << ' ' << e << '\n';
    return 0;
}
