#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R = random.randint(1, 10**9)  # TODO: edit here
    C = random.randint(1, 10**9)  # TODO: edit here
    N = random.randint(1, 1000)  # TODO: edit here
    r = [None for _ in range(N)]
    c = [None for _ in range(N)]
    a = [None for _ in range(N)]
    for i in range(N):
        r[i] = random.randint(1, 10**9)  # TODO: edit here
        c[i] = random.randint(1, 10**9)  # TODO: edit here
        a[i] = random.randint(1, 10**9)  # TODO: edit here
    print(R, C)
    print(N)
    for i in range(N):
        print(r[i], c[i], a[i])


if __name__ == "__main__":
    main()
