#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

std::vector<std::vector<char>> solve(auto H, auto W, const std::vector<std::vector<char>> &a)
{
    std::vector<std::vector<char>> ans = a;

    int removed = 0;
    do
    {
        removed = 0;
        // 行削除
        REP_R(i, ans.size())
        {
            if (all_of(ALL(ans[i]), [&](auto c)
                       { return c == '.'; }))
            {
                ans.erase(ans.begin() + i);
                removed++;
            }
        }
        // 列削除
        REP_R(j, ans.front().size())
        {
            if (all_of(ALL(ans), [&](auto row)
                       { return row[j] == '.'; }))
            {
                REP(i, ans.size())
                {
                    ans[i].erase(ans[i].begin() + j);
                }
                removed++;
            }
        }
    } while (removed > 0);

    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int H, W;
    std::cin >> H >> W;
    std::vector<std::vector<char>> a(H, std::vector<char>(W));
    REP(i, H)
    {
        REP(j, W)
        {
            std::cin >> a[i][j];
        }
    }
    auto ans = solve(H, W, a);
    for (auto row : ans)
    {
        for (auto c : row)
        {
            std::cout << c;
        }
        std::cout << '\n';
    }
    return 0;
}
