#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(std::string S)
{
    int64_t removed, ans = 0;
    do
    {
        removed = 0;
        vector<string> ss = {"01", "10"};
        for (auto target : ss)
        {
            vector<int> remove_index_list;
            for (auto it = S.begin(); it < S.end() - 1; it++)
            {
                if (*it == target[0] && *(it + 1) == target[1])
                {
                    remove_index_list.push_back(it - S.begin());
                }
            }
            for (auto it = remove_index_list.rbegin(); it != remove_index_list.rend(); it++)
            {
                S.erase(*it, 2);
                removed += 2;
            }
        }
        ans += removed;
    } while (removed > 0);

    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::string S;
    std::cin >> S;
    auto ans = solve(S);
    std::cout << ans << '\n';
    return 0;
}
