#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(auto H, auto W, auto N, const std::vector<auto> &a, const std::vector<auto> &b) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto H, W, N;
    std::cin >> H >> W >> N;
    std::vector<auto> a(N), b(N);
    REP (i, N) {
        std::cin >> a[i] >> b[i];
    }
    auto ans = solve(H, W, N, a, b);
    std::cout << ans << '\n';
    return 0;
}
