#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    M = random.randint(1, 1000)  # TODO: edit here
    d = [None for _ in range(M)]
    c = [None for _ in range(M)]
    for i in range(M):
        d[i] = random.randint(1, 10**9)  # TODO: edit here
        c[i] = random.randint(1, 10**9)  # TODO: edit here
    print(M)
    for i in range(M):
        print(d[i], c[i])


if __name__ == "__main__":
    main()
