#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    lx = [None for _ in range(N)]
    ly = [None for _ in range(N)]
    rx = [None for _ in range(N)]
    ry = [None for _ in range(N)]
    for i in range(N):
        lx[i] = random.randint(1, 10**9)  # TODO: edit here
        ly[i] = random.randint(1, 10**9)  # TODO: edit here
        rx[i] = random.randint(1, 10**9)  # TODO: edit here
        ry[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    for i in range(N):
        print(lx[i], ly[i], rx[i], ry[i])


if __name__ == "__main__":
    main()
