#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, const std::vector<int64_t> &lx, const std::vector<int64_t> &ly, const std::vector<int64_t> &rx, const std::vector<int64_t> &ry) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> lx(N), ly(N), rx(N), ry(N);
    REP (i, N) {
        std::cin >> lx[i] >> ly[i] >> rx[i] >> ry[i];
    }
    auto ans = solve(N, lx, ly, rx, ry);
    REP (i, N) {
        std::cout << A[i] << '\n';
    }
    return 0;
}
