#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t N, int64_t A, int64_t B)
{
    if (A > B)
    {
        return 0;
    }
    if (N == 1)
    {
        return A == B ? 1 : 0;
    }
    return views::iota((N - 1) * A + B, A + (N - 1) * B + 1).size();
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, A, B;
    std::cin >> N >> A >> B;
    auto ans = solve(N, A, B);
    std::cout << ans << '\n';
    return 0;
}
