#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const int ROUND = 7;
double solve(int P)
{
    double win = double(P) / 100,
           lose = double(100 - P) / 100,
           ans = 0.0;
    for (auto i = 0; i < (1 << ROUND); i++)
    {
        bitset<ROUND> bs(i);
        if (bs.count() > ROUND / 2)
        {
            ans += pow(win, bs.count()) * pow(lose, ROUND - bs.count());
        }
    }
    return ans * 100;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int P;
    std::cin >> P;
    auto ans = solve(P);
    std::cout << fixed << setprecision(10) << ans << '\n';
    return 0;
}
