#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int H, int64_t W, const std::vector<std::string> &S) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int H;
    int64_t W;
    std::cin >> H;
    std::vector<std::string> S(H);
    std::cin >> W;
    REP (i, H) {
        std::cin >> S[i];
    }
    auto ans = solve(H, W, S);
    REP (i, H) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
