#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t N, std::string S)
{
    int64_t ans = 0;
    REP3(i, 1, N - 1)
    {
        string left_S = S.substr(0, i);
        set<char> left = set<char>(ALL(left_S));
        string right_S = S.substr(i);
        set<char> right = set<char>(ALL(right_S));
        vector<char> intersection;
        set_intersection(ALL(left), ALL(right), back_inserter(intersection));
        ans = max(ans, (int64_t)intersection.size());
    }
    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    std::string S;
    std::cin >> N >> S;
    auto ans = solve(N, S);
    std::cout << ans << '\n';
    return 0;
}
