#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 998244353;
auto solve(int N, std::vector<int64_t> &A, int Q, const std::vector<int64_t> &B)
{
    sort(ALL(A));

    vector<int64_t> ans(Q);
    REP(i, Q)
    {
        auto t = lower_bound(ALL(A), B[i]);
        int64_t diff = t == A.begin() ? abs(B[i] - *t) : min(abs(B[i] - *t), abs(B[i] - *(t - 1)));
        ans[i] = diff;
    }

    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, Q;
    std::cin >> N;
    std::vector<int64_t> A(N);
    REP(i, N)
    {
        std::cin >> A[i];
    }
    std::cin >> Q;
    std::vector<int64_t> B(Q);
    REP(i, Q)
    {
        std::cin >> B[i];
    }
    for (auto ans : solve(N, A, Q, B))
    {
        std::cout << ans << '\n';
    }
    return 0;
}
