#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string FIRST = "alice";
const std::string SECOND = "bob";
vector<string> solve(int N, const std::vector<std::string> &S, const std::vector<int64_t> &A)
{
    int64_t start = ranges::min_element(A) - begin(A);

    vector<string> ans;
    REP3(i, start, S.size())
    {
        ans.push_back(S[i]);
    }
    REP(i, start)
    {
        ans.push_back(S[i]);
    }
    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<std::string> S(N);
    std::vector<int64_t> A(N);
    REP(i, N)
    {
        std::cin >> S[i] >> A[i];
    }
    auto ans = solve(N, S, A);
    REP(i, N)
    {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
