#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = [None for _ in range(64)]
    for i in range(64):
        A[i] = random.randint(1, 10**9)  # TODO: edit here
    print(*[A[i] for i in range(64)])


if __name__ == "__main__":
    main()
