#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

uint64_t solve(const std::vector<uint64_t> &A)
{
    uint64_t ans = 0;
    REP(i, A.size())
    {
        if (A[i] == 1)
        {
            uint64_t n = 1;
            REP(j, i)
            {
                n *= 2;
            }
            ans += n;
        }
    }
    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::vector<uint64_t> A(64);
    REP(i, 64)
    {
        std::cin >> A[i];
    }
    auto ans = solve(A);
    std::cout << ans << '\n';
    return 0;
}
