#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, const std::vector<int64_t> &X, const std::vector<int64_t> &Y)
{
    // 高橋くんの状態 := 普通 or お腹を壊している
    // dp[i番目の料理][高橋くんの状態] = 美味しさの総和の最大値
    vector<vector<int64_t>> dp(N + 1, vector<int64_t>(2, -1e18));
    dp[0] = {0, 0};
    REP(i, N)
    {
        // 下げてもらう場合
        dp[i + 1][0] = max(dp[i + 1][0], dp[i][0]);
        dp[i + 1][1] = max(dp[i + 1][1], dp[i][1]);

        if (X[i] == 0)
        {
            dp[i + 1][0] = max({dp[i + 1][0], dp[i][0] + Y[i], dp[i][1] + Y[i]});
        }
        if (X[i] == 1)
        {
            dp[i + 1][1] = max({dp[i + 1][1], dp[i][0] + Y[i]});
        }
    }
    return *ranges::max_element(dp.back());
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> X(N), Y(N);
    REP(i, N)
    {
        std::cin >> X[i] >> Y[i];
    }
    auto ans = solve(N, X, Y);
    std::cout << ans << '\n';
    return 0;
}
