#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    P = [None for _ in range(N - 1)]
    B = [None for _ in range(N)]
    W = [None for _ in range(N)]
    C = [None for _ in range(N)]
    X = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N - 1):
        P[i] = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N):
        B[i] = random.randint(1, 10**9)  # TODO: edit here
        W[i] = random.randint(1, 10**9)  # TODO: edit here
        C[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, X)
    print(*[P[i] for i in range(N - 1)])
    for i in range(N):
        print(B[i], W[i], C[i])


if __name__ == "__main__":
    main()
