#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t R, int64_t G, int64_t B, int64_t N)
{
    int64_t ans = 0;
    REP(r, N / R + 1)
    {
        REP(g, N / G + 1)
        {
            auto b = (N - R * r - G * g) / B;
            if (b >= 0 and R * r + G * g + B * b == N)
            {
                ans++;
            }
        }
    }
    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t R, G, B, N;
    std::cin >> R >> G >> B >> N;
    auto ans = solve(R, G, B, N);
    std::cout << ans << '\n';
    return 0;
}
