#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 1000000007;
int64_t solve(int N, const std::vector<vector<int64_t>> &A)
{
    int64_t ans = 1;
    REP(i, N)
    {
        ans *= accumulate(ALL(A[i]), 0LL);
        ans %= MOD;
    }
    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<vector<int64_t>> A(N, vector<int64_t>(6));
    REP(i, N)
    {
        REP(j, 6)
        {
            std::cin >> A[i][j];
        }
    }
    auto ans = solve(N, A);
    std::cout << ans << '\n';
    return 0;
}
