#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    C = [None for _ in range(N + 1)]
    for i in range(N):
        A[i] = random.randint(1, 10**9)  # TODO: edit here
        B[i] = random.randint(1, 10**9)  # TODO: edit here
    for i in range(N + 1):
        C[i] = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    D = [None for _ in range(Q)]
    E = [None for _ in range(Q)]
    for i in range(Q):
        D[i] = random.randint(1, 10**9)  # TODO: edit here
        E[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    for i in range(N):
        print(A[i], B[i])
    print(*[C[i] for i in range(N + 1)])
    print(Q)
    for i in range(Q):
        print(D[i], E[i])


if __name__ == "__main__":
    main()
