#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(auto N, const std::vector<auto> &A, auto M, const std::vector<auto> &B, auto command) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M, command;
    std::cin >> N;
    std::vector<auto> A(N);
    REP (i, N) {
        std::cin >> A[i];
    }
    std::cin >> M;
    std::vector<auto> B(M);
    REP (i, M) {
        std::cin >> B[i];
    }
    std::cin >> command;
    auto ans = solve(N, A, M, B, command);
    // failed to analyze output format
    // TODO: edit here
    std::cout << ans << '\n';
    return 0;
}
