#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const string SNUKE = "snuke";
const vector<pair<int, int>> dxdy = {
    {0, -1},
    {0, 1},
    {-1, 0},
    {1, 0},
    {-1, -1},
    {1, -1},
    {-1, 1},
    {1, 1},
};
vector<pair<int, int>> solve(int H, int W, const std::vector<std::string> &S)
{
    vector<pair<int, int>> ans(5);
    REP(y, H)
    REP(x, W)
    {
        if (S[y][x] != SNUKE[0])
        {
            continue;
        }
        ans[0] = {y + 1, x + 1};

        for (auto [dx, dy] : dxdy)
        {
            bool correct = true;
            auto nx = x,
                 ny = y;
            REP3(i, 1, 5)
            {
                nx += dx;
                ny += dy;
                ans[i] = {ny + 1, nx + 1};
                if (!(0 <= nx and nx < W and 0 <= ny and ny < H and S[ny][nx] == SNUKE[i]))
                {
                    correct = false;
                    break;
                }
            }
            if (correct)
            {
                return ans;
            }
        }
    }
    return {};
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int H, W;
    std::cin >> H >> W;
    std::vector<std::string> S(H);
    REP(i, H)
    {
        std::cin >> S[i];
    }
    auto ans = solve(H, W, S);
    REP(i, 5)
    {
        std::cout << ans[i].first << ' ' << ans[i].second << '\n';
    }
    return 0;
}
