#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, const std::vector<int64_t> &a)
{
    vector<int64_t> button(N);
    REP(i, N)
    {
        button[i] = a[i] - 1;
    }

    vector<bool> pushed(N, false);
    int64_t index = 0, ans = 0;
    while (true)
    {
        if (index + 1 == 2)
        {
            return ans;
        }
        if (pushed[index])
        {
            return -1;
        }

        pushed[index] = true;
        index = button[index];
        ans++;
    }
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> a(N);
    REP(i, N)
    {
        std::cin >> a[i];
    }
    auto ans = solve(N, a);
    std::cout << ans << '\n';
    return 0;
}
