#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t N, vector<string> &S)
{
    int64_t ans = 0;
    for (auto s : S)
    {
        if (s == "WA" or s == "-")
        {
            ans++;
        }
    }
    return ans * 5;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    std::cin >> N;
    vector<string> S(N);
    REP(i, N)
    {
        cin >> S[i];
    }
    auto ans = solve(N, S);
    std::cout << ans << '\n';
    return 0;
}
