#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t N, int64_t M, std::string S, std::string T)
{
    bool is_prefix = T.starts_with(S),
         is_suffix = T.ends_with(S);
    if (is_prefix && is_suffix)
    {
        return 0;
    }
    if (is_prefix)
    {
        return 1;
    }
    if (is_suffix)
    {
        return 2;
    }
    return 3;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, M;
    std::string S, T;
    std::cin >> N >> M >> S >> T;
    auto ans = solve(N, M, S, T);
    std::cout << ans << '\n';
    return 0;
}
