#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    X = [None for _ in range(N)]
    P = [None for _ in range(N - 1)]
    F = [None for _ in range(N - 1)]
    H = random.randint(1, 10)  # TODO: edit here
    for i in range(N):
        X[i] = random.randint(1, 10)  # TODO: edit here
    for i in range(N - 1):
        P[i] = random.randint(1, 10)  # TODO: edit here
        F[i] = random.randint(1, 10)  # TODO: edit here
    print(N, H)
    print(*[X[i] for i in range(N)])
    for i in range(N - 1):
        print(P[i], F[i])


if __name__ == "__main__":
    main()
