#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(auto N, auto H, const std::vector<auto> &X, const std::vector<auto> &P, const std::vector<auto> &F) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, H;
    std::cin >> N;
    std::vector<auto> X(N), P(N - 1), F(N - 1);
    std::cin >> H;
    REP (i, N) {
        std::cin >> X[i];
    }
    REP (i, N - 1) {
        std::cin >> P[i] >> F[i];
    }
    auto ans = solve(N, H, X, P, F);
    std::cout << ans << '\n';
    return 0;
}
