#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const string YES = "Yes";
const string NO = "No";
bool solve(int64_t N, vector<string> &aop)
{
    vector<int64_t> results;
    int64_t result = 0;
    REP(i, aop.size())
    {
        if (aop[i] == "=")
        {
            results.push_back(result);
            result = 0;
        }
        else if (aop[i] != "+")
        {
            result += stoi(aop[i]);
        }
    }
    results.push_back(result);

    REP(i, results.size())
    {
        if (results[i] != results[0])
        {
            return false;
        }
    }
    return true;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    std::cin >> N;
    vector<string> aop(2 * N + 1);
    REP(i, aop.size())
    {
        cin >> aop[i];
    }
    auto ans = solve(N, aop);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
