#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = random.randint(1, 10**9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    for i in range(Q):
        l[i] = random.randint(1, 10**9)  # TODO: edit here
        r[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N)
    print(*[A[i] for i in range(N)])
    print(Q)
    for i in range(Q):
        print(l[i], r[i])


if __name__ == "__main__":
    main()
