#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(auto N, auto M, const std::vector<auto> &L, const std::vector<auto> &R, const std::vector<auto> &D) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M;
    std::cin >> N >> M;
    std::vector<auto> L(M), R(M), D(M);
    REP (i, M) {
        std::cin >> L[i] >> R[i] >> D[i];
    }
    auto ans = solve(N, M, L, R, D);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
