#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10**9)  # TODO: edit here
    M = random.randint(1, 1000)  # TODO: edit here
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    W = [None for _ in range(M)]
    for i in range(M):
        U[i] = random.randint(1, 10**9)  # TODO: edit here
        V[i] = random.randint(1, 10**9)  # TODO: edit here
        W[i] = random.randint(1, 10**9)  # TODO: edit here
    K = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(K)]
    for i in range(K):
        A[i] = random.randint(1, 10**9)  # TODO: edit here
    D = random.randint(1, 1000)  # TODO: edit here
    X = [None for _ in range(D)]
    for i in range(D):
        X[i] = random.randint(1, 10**9)  # TODO: edit here
    print(N, M)
    for i in range(M):
        print(U[i], V[i], W[i])
    print(K)
    print(*[A[i] for i in range(K)])
    print(D)
    print(*[X[i] for i in range(D)])


if __name__ == "__main__":
    main()
