#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, int64_t T, std::vector<int64_t> &t)
{
    int64_t ans = 0;
    REP(i, N - 1)
    {
        ans += min(T, t[i + 1] - t[i]);
    }
    return ans + T;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t T;
    std::cin >> N;
    std::vector<int64_t> t(N);
    std::cin >> T;
    REP(i, N)
    {
        std::cin >> t[i];
    }
    auto ans = solve(N, T, t);
    std::cout << ans << '\n';
    return 0;
}
