#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(auto N, auto T, auto M, const std::vector<auto> &A, const std::vector<auto> &B) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, T, M;
    std::cin >> N >> T >> M;
    std::vector<auto> A(M), B(M);
    REP (i, M) {
        std::cin >> A[i] >> B[i];
    }
    auto ans = solve(N, T, M, A, B);
    std::cout << ans << '\n';
    return 0;
}
