#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int H, int W, const std::vector<vector<char>> &s)
{
    vector<vector<char>> padded_s(H + 2, vector<char>(W + 2, '.'));
    REP(i, H)
    {
        REP(j, W)
        {
            padded_s[i + 1][j + 1] = s[i][j];
        }
    }

    REP3(i, 1, H + 1)
    {
        REP3(j, 1, W + 1)
        {
            if (padded_s[i][j] == '#')
            {
                if (padded_s[i - 1][j] == '.' && padded_s[i + 1][j] == '.' && padded_s[i][j - 1] == '.' && padded_s[i][j + 1] == '.')
                {
                    return false;
                }
            }
        }
    }
    return true;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int H, W;
    std::cin >> H >> W;
    std::vector<vector<char>> s(H, vector<char>(W));
    REP(i, H)
    {
        REP(j, W)
        {
            std::cin >> s[i][j];
        }
    }
    auto ans = solve(H, W, s);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
