#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int N, const std::vector<int64_t> &p, const std::vector<int64_t> &t, const std::vector<int64_t> &s, const std::vector<int64_t> &g) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> p(N - 1), t(N - 1), s(N - 1), g(N - 1);
    REP (i, N - 1) {
        std::cin >> p[i] >> t[i] >> s[i] >> g[i];
    }
    auto ans = solve(N, p, t, s, g);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
