#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, int64_t P, int64_t Q, const std::vector<int64_t> &A)
{
    int64_t ans = 0;

    REP(i, N)
    {
        REP3(j, i + 1, N)
        {
            REP3(k, j + 1, N)
            {
                REP3(l, k + 1, N)
                {
                    REP3(m, l + 1, N)
                    {
                        if (A[i] * A[j] % P * A[k] % P * A[l] % P * A[m] % P == Q)
                        {
                            ans++;
                        }
                    }
                }
            }
        }
    }

    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t P, Q;
    std::cin >> N;
    std::vector<int64_t> A(N);
    std::cin >> P >> Q;
    REP(i, N)
    {
        std::cin >> A[i];
    }
    auto ans = solve(N, P, Q, A);
    std::cout << ans << '\n';
    return 0;
}
