#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

std::pair<int64_t, int64_t> solve(int N, const std::vector<int64_t> &A)
{
    map<int64_t, int64_t> count;
    for (auto a : A)
    {
        count[a]++;
    }
    return *max_element(ALL(count), [](auto a, auto b)
                        { return a.second < b.second; });
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    std::cin >> N;
    std::vector<int64_t> A(N);
    REP(i, N)
    {
        std::cin >> A[i];
    }
    auto [c, d] = solve(N, A);
    std::cout << c << ' ' << d << '\n';
    return 0;
}
