#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    M = random.randint(1, 10)  # TODO: edit here
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    K = random.randint(1, 10)  # TODO: edit here
    p = [None for _ in range(K)]
    h = [None for _ in range(K)]
    for i in range(M):
        a[i] = random.randint(1, 10)  # TODO: edit here
        b[i] = random.randint(1, 10)  # TODO: edit here
    for i in range(K):
        p[i] = random.randint(1, 10)  # TODO: edit here
        h[i] = random.randint(1, 10)  # TODO: edit here
    print(N, M, K)
    for i in range(M):
        print(a[i], b[i])
    for i in range(K):
        print(p[i], h[i])


if __name__ == "__main__":
    main()
