#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


std::vector<int64_t> solve(auto N, auto M, auto K, const std::vector<auto> &a, const std::vector<auto> &b, const std::vector<auto> &p, const std::vector<auto> &h) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M, K;
    std::cin >> N >> M;
    std::vector<auto> a(M), b(M);
    std::cin >> K;
    std::vector<auto> p(K), h(K);
    REP (i, M) {
        std::cin >> a[i] >> b[i];
    }
    REP (i, K) {
        std::cin >> p[i] >> h[i];
    }
    auto ans = solve(N, M, K, a, b, p, h);
    std::cout << (int)ans.size() << '\n';
    REP (i, (int)ans.size()) {
        std::cout << v[i] << ' ';
    }
    std::cout << '\n';
    return 0;
}
