#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = random.randint(1, 10**9)  # TODO: edit here
    H = random.randint(1, 10**9)  # TODO: edit here
    S = random.randint(1, 10**9)  # TODO: edit here
    D = random.randint(1, 10**9)  # TODO: edit here
    N = random.randint(1, 10**9)  # TODO: edit here
    print(Q, H, S, D)
    print(N)


if __name__ == "__main__":
    main()
