#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t Q, int64_t H, int64_t S, int64_t D, int64_t N)
{
    int64_t q = Q * 4;
    int64_t h = H * 2;
    int64_t s = S;
    int64_t least = min({q * 2, h * 2, s * 2, D});
    return N / 2 * least + N % 2 * min({q, h, s});
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t Q, H, S, D, N;
    std::cin >> Q >> H >> S >> D >> N;
    auto ans = solve(Q, H, S, D, N);
    std::cout << ans << '\n';
    return 0;
}
