#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t A, int64_t B, int64_t C)
{
    int64_t ans = 0;
    while (A != B || B != C)
    {
        if (max({A, B, C}) - min({A, B, C}) >= 2)
        {
            if (A < B && A < C)
            {
                A += 2;
            }
            else if (B < A && B < C)
            {
                B += 2;
            }
            else
            {
                C += 2;
            }
        }
        else
        {
            if (A <= C && B <= C)
            {
                A++;
                B++;
            }
            else if (A <= B && C <= B)
            {
                A++;
                C++;
            }
            else
            {
                B++;
                C++;
            }
        }
        ans++;
    }
    return ans;
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main()
{
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t A, B, C;
    std::cin >> A >> B >> C;
    auto ans = solve(A, B, C);
    std::cout << ans << '\n';
    return 0;
}
